CLASE6/CLASE6/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('NewsPaperApp.urls'))
]

urlpatterns += static(
    settings.MEDIA_URL, 
    document_root = settings.MEDIA_ROOT
    )

CLASE6/NewsPaPerApp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path(
        '', 
        views.Index,
        name="index"
    ),
    path(
        'list/', 
        views.ListNews,
        name="listNews"
    ),
    path(
        'detail/<int:id>/', 
        views.DetailNews,
        name="detailNew"
    ),
]

CLASE6/NewsPaPerApp/models.py
from django.db import models

# Create your models here.


class Theme(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Journalist(models.Model):
    name = models.CharField(max_length=40)
    lastName = models.CharField(max_length=40)
    image_profile = models.ImageField(null=True)
    themes = models.ManyToManyField(Theme)

    def __str__(self):
        return "{0}, {1}".format(
            self.lastName,
            self.name
        )


class News(models.Model):

    state_of_news = [
        ("E", "Editando"),
        ("P", "Publicado"),
        ("B", "Bloqueado")
    ]

    state = models.CharField(
        max_length=2,
        choices=state_of_news,
        default="E"
    )
    name = models.DateTimeField(auto_now_add=True)
    publish_date = models.DateTimeField(null=True)
    last_update_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    detail = models.CharField(max_length=300)
    write_by = models.ForeignKey(
        Journalist,
        on_delete=models.CASCADE
    )
    main_image = models.ImageField(null=True)

    def __str__(self):
        return self.title

    class Images(models.Model):
        news = models.ForeignKey(
            News,
            on_delete=models.CASCADE
            )
        image = models.ImageField()

CLASE6/NewsPaPerApp/views.py
from django.db.models import query
from django.shortcuts import render
from .models import News, Journalist
# Create your views here.


def Index(request):
    """
    Al entrar al index vamos a ver las utimas noticias
    """
    return render(
        request,
        'NewsPaperApp/index.html',
        {}
    )


def ListNews(request):
    query = News.objects.all().order_by('publish_date')
    return render(
        request,
        'NewsPaperApp/list-news.html',
        {"list": query}
    )


def DetailNews(request, id):
    query = News.objects.get(id=id)
    return render(
        request,
        'NewsPaperApp/detail-news.html',
        {'new': query}
    )

CLASE6/NewsPaPerApp/templates/NewsPaperApp/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'NewsPaperApp/css/style.css'%}">
</head>
<body>
    <header>
        <img src="{% static 'NewsPaperApp/assert/infobae.png' %}" alt="infobae logo" class="logo">
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'listNews' %}">Noticas</a></li>
                <li><a href="">Contactanos</a></li>

            </ul>
        </nav>
    </header>
    {% block main %} {% endblock %}
</body>
</html>

CLASE6/NewsPaPerApp/templates/NewsPaperApp/basic_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'NewsPaperApp/css/style.css' %}">
</head>
<body>
    <header>
        <img src="{% static 'NewsPaperApp\assert\infobae.png' %}" alt="infobae logo" class="logo">
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'listNews' %}">Noticias</a></li>
                <li><a href="">Contactanos</a></li>
            </ul>
        </nav>
    </header>
    {% block main %}
    {% endblock %}
</body>
</html>

CLASE6/NewsPaPerApp/templates/NewsPaperApp/detail-news.html
{% extends 'NewsPaperApp/base_generic.html' %}

{% block title %}
    La notica
{% endblock %}

{% block main %}
    <h1> {{new.title }} </h1>
    <p> {{new.detail}} </p>
    <img style="height:  300px;" src="{{ new.main_image.url }}" alt="">
    {% for image in  new.images_set.all %}
        <img style="height:  300px;" src="{{ image.image.url }}" alt="">
    {% endfor %}
    <br>
    <br>
    <br>
    <br>
    <img style="height:  300px; border-radius: 3000px;" src="{{ new.write_by.image_profile.url }}" alt="">
    {{new.write_by.lastname}}- {{new.write_by.name}}
{% endblock %}

CLASE6/NewsPaPerApp/templates/NewsPaperApp/index.html
{% extends 'NewsPaperApp/base_generic.html' %}

{% block title %}
    Binevenido
{% endblock %}

{% block main %}
    <p> Bienvenido al index</p>
{% endblock %}

CLASE6/NewsPaPerApp/templates/NewsPaperApp/list-news.html
{% extends 'NewsPaperApp/base_generic.html' %}

{% block title %}
    Todas las noticias
{% endblock %}

{% block main %}
    <p>Lista de noticas</p>
    <article class="news">
        {% for item in list %}
        <section>
            <img src="{{ item.main_image.url }}" alt="">
            <div>
                <h5>{{item.title}}</h5>
                <p>{{item.detail}}</p>
                <a href="{% url 'detailNew' item.id %}"> Leer mas </a>
                <p class="small"> Escrito por {{item.write_by.lastname}},{{item.write_by.name}} el {{item.publish_date}} </p>    
            </div>
        </section>
        {% endfor %}
    </article>
{% endblock %}