CLASE5/BookStore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('books/', views.BookList, name="bookList"),
    path('editorials/', views.EditorialList, name="editorialList"),
    path('authors/', views.AuthorList, name="authorList"),
    path('book/<int:id>/', views.BookDetail, name="bookDetail"),
    path('author/<int:id>/', views.AuthorDetail, name="authorDetail"),
    path('editorial/<int:id>/', views.EditorialDetail, name="editorialDetail"),

]

CLASE5/CLASE5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('BookStore.urls')),
    
]

CLASE5/BookStore/models.py
from django.db import models

# Create your models here.

class Editorial(models.Model):
    name = models.CharField(max_length=150)
    adress = models.CharField(max_length=400)

    def __str__(self):
        return "{0}".format(self.name)

class Author(models.Model):
    name = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)

    def __str__(self):
        return "{0}, {1}".format(self.lastname, self.name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    sysnopsis = models.CharField(max_length=300)
    editorial = models.ForeignKey(
        Editorial,
        on_delete=models.CASCADE
    )
    authors = models.ManyToManyField(Author)
    price = models.IntegerField(default=0)
    publish_date = models.DateTimeField(default=None, null=True)
    #authors = models.ManyToManyField(Author, through='Entidad extra')

    def __str__(self):
        return "{0}".format(self.title)

# class EntidadExtra():
#     Definir campos extra para esa tabla. 

CLASE5/BookStore/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render
from .models import Book, Author, Editorial
# Create your views here.


def BookList(request):
    #Esto me trea una lista con todos los libros en BD.
    query = Book.objects.all()
    return render(
        request,
        'BookStore/book-list.html',
        { 'bookList' : query}
    )

def BookDetail(request, id):
    #El primer id es el campo en base de datos, y el segundo es el parametro que recibi.
    query = Book.objects.get(id=id)
    return render(
        request,
        'BookStore/book-detail.html',
        { 'book' : query}
    )

def AuthorList(request):
    query = Author.objects.all()
    return render(
        request,
        'BookStore/author-list.html',
        { 'authorList' : query}
    )

def AuthorDetail(request, id):
    # Se puede utilizar get o filter
    query = Author.objects.get(id=id)
    return render(
        request,
        'BookStore/author-detail.html',
        { 'author' : query}
    )

def EditorialList(request):
    query = Editorial.objects.all()
    
    return render(
        request,
        'BookStore/editorial-list.html',
        {'editorialList' : query}
    )

def EditorialDetail(request, id):
    query = Editorial.objects.get(id=id)
    return render(
        request,
        'BookStore/editorial-detail.html',
        {'editorial' : query}
    )

CLASE5/BookStore/templates/BookStore/author-detail.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Detalle {% endblock %}

{% block body %}
    <p>{{author.name}}</p>
    <p>{{author.lastname}}</p>
    <ul>
        {% for book in author.book_set.all %}
            <li> 
                <a href="{% url 'bookDetail' book.id %}">
                    {{book.title}} 
                </a> 
            </li>
        {% endfor %}
    </ul>
{% endblock %}

CLASE5/BookStore/templates/BookStore/author-list.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Lista {% endblock %}

{% block body %}
    <h3> Lista de autores </h3>
    <ul>
        {% for author in authorList %}
            <li> <a href="{% url 'authorDetail' author.id %}">{{author.name}} {{author.lastname}}</a>  </li>
        {% endfor %}
    </ul>
{% endblock %}

CLASE5/BookStore/templates/BookStore/base-generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <div class="d-flex flex-row ">
        <div class="col-8 d-flex justify-content-between">
            <nav class="nav d-flex align-items-center">
                <a class="nav-link active fs-3" aria-current="page" href="{% url 'BookList' %}">Lista de libros</a>
                <a class="nav-link active fs-3" href="{% url 'AuthorList' %}">Lista de autores</a>
                <a class="nav-link active fs-3" href="{% url 'EditorialList' %}">Lista de editoriales</a>
            </nav>
        </div>
        <div class="col-4 d-flex justify-content-center">
            <h1 class="display-3">LIBRERIA</h1>
        </div>
    </div>
    {% block body %}


    {% endblock %}

    
    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

</body>

</html>

CLASE5/BookStore/templates/BookStore/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light navbar-dark bg-primary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar w/ text</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookList'%}">Libros</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'authorList'%}">Autores</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'editorialList'%}">Editoriales</a>
                  </li>
                </ul>

              </div>
            </div>
          </nav>
    </header>
    {% block body %} {% endblock %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

CLASE5/BookStore/templates/BookStore/book-detail.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Detalle {% endblock %}

{% block body %}
    <p> title : {{book.title}}</p>
    <p> precio : {{book.price}}</p>
    <p> Sinosis : {{ book.sysnopsis }} </p>
    <p> Editorial :
        <a href="{% url 'editorialDetail' book.editorial.id %}">
            {{book.editorial}}
        </a>
    </p>
    <!-- PENDIENTE -->
    <p> Autores : </p>
    <ul>
        {% for author in book.authors.all %}
        <li>
            <a href="{% url 'authorDetail' author.id %}">
                {{author.name}} {{author.lastname}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

CLASE5/BookStore/templates/BookStore/book-list.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Lista {% endblock %}

{% block body %}
    <h3> Lista de libros </h3>
    <ul>
        {% for book in bookList %}
            <li> <a href="{% url 'bookDetail' book.id %}">{{book.title}}</a>  </li>
        {% endfor %}
    </ul>
{% endblock %}

CLASE5/BookStore/templates/BookStore/editorial-detail.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Detalle {% endblock %}

{% block body %}
    <p> Nombre : {{editorial.name}}</p>
    <p>Direccion : {{editorial.adress}}  </p>
    <h4> Lista de titulos </h4>
    <ul>
    {% for book in editorial.book_set.all %}
        <li> <a href="{% url 'bookDetail' book.id %}"> {{book.title}} </a></li>
    {% endfor %}

    </ul>
{% endblock %}

CLASE5/BookStore/templates/BookStore/editorial-list.html
{% extends 'BookStore/base_generic.html' %}

{% block title %} Lista {% endblock %}

{% block body %}
    
    <h3> Lista de editoriales </h3>
    <ul>
        {% for editorial in editorialList %}
            <li> <a href="{% url 'editorialDetail' editorial.id %}">{{editorial.name}}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}